### ISSUE TITLE
'trace' importing error

### ISSUE THREAD

**Issue by WURdamian** [ngaggion/ChronoRoot#1]
I've been trying to get ChronoRoot to work. 
First I had to downgrade TensorFlow to version 1.15 as contrib was missing in the newer versions.
However after doing that; now I have another error while running a first test of segmentation:
python segmentFast.py D:\chronoroottest\input\1.tif D:\chronoroottest\output optionalSegPath --use_crf boolean --model ResUNetDS

The error is the following: **ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (C:\Users\user\.conda\envs\tf15\lib\site-packages\tensorflow_core\python\profiler\__init__.py)**
I cannot find anywhere online how to resolve the issue, is there anything missing in the files?

**Comment by ngaggion** [comment]
Hello, I do not recognize this error. Some weeks ago I made an [installation tutorial](
https://docs.google.com/presentation/d/1_qIMuLRUYua0Ru3l6yfqty0AaSQsKu8HpN3NpCHFeC0/edit?usp=sharing) as it was requested by some biologists. I'm sharing it with you, maybe with a clean install you won't have errors. 
We are planning to move the project to a docker soon, to avoid these kind of inconveniences.
